export interface ITypesActions {
  GET_INGREDIENTS: string;
  GET_INGREDIENTS_SUCCESS: string;
  GET_INGREDIENTS_ERROR: string;
  ADD_INGREDIENT: string,
  DECREASE_INGREDIENT: string
}

export const typesActions: ITypesActions= {
  GET_INGREDIENTS: 'GET_INGREDIENTS',
  GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS',
  GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR',
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  DECREASE_INGREDIENT: 'DECREASE_INGREDIENT'
}